"""
llm_sar_narrator.py

OPTIONAL enhancement layer. Uses the same Groq LLM as llm_intent_parser.py
to write a narrative lead sentence for the SAR draft box, grounded strictly
in that row's own real fields (party, amount, reason) -- it can rephrase
and contextualize, but the prompt is designed so it cannot introduce facts
not already present in the row data.

Only ever called for the first ~20 displayed rows (executor.py), never the
full flagged set -- so cost/latency/rate-limit exposure stays bounded
regardless of how many rows a query flags.

Not a replacement for the deterministic SAR block -- the "Basis for flag" /
"Recommended action" lines stay exactly as generated by explanation_engine.py.
This only adds one narrative sentence on top. Raises on any failure (missing
key, network error, timeout, malformed response); the caller falls back to
no narrative sentence (today's plain template, unchanged).
"""

import os
import re
import time
import requests

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "llama-3.1-8b-instant"  # fast, free-tier model

SYSTEM_PROMPT = """You write ONE short, compliance-appropriate narrative sentence summarizing a flagged financial transaction for a Suspicious Activity Report.

Rules:
- Use ONLY the facts given below. Do not invent amounts, dates, counts, or patterns not stated.
- Exactly one sentence, no more than 30 words.
- Plain, factual, regulatory tone -- no hype, no speculation about intent or identity.
- If given a "Confidence context" line, you MUST include its exact percentage figure
  verbatim in your sentence (e.g. "roughly 67%") -- never a different number, never a
  rounded-off score value, and never a vague substitute like "high confidence" alone.
- Do not restate "Recommended action" -- that is added separately below your sentence.
- Respond with ONLY the sentence itself. No quotes, no markdown, no preamble.
"""

# Precision bands validated against isFraud for ML-only (rule-independent) catches --
# see risk_classifier.py and the README's "ML-anomaly query's risk tiers" note. Used
# to give the LLM something real and specific to say instead of just re-describing
# the same anomaly score already printed on the explanation line above it.
# expected_pct is used to validate the model's response below -- if the sentence
# names a different percentage, that's a hallucination (likely the model confusing
# this with the raw 0-1 anomaly score), and the caller falls back rather than show it.
_ML_ONLY_TIER_CONTEXT = {
    "HIGH": {
        "note": "This falls in the model's top anomaly-score band, which validated at "
                "roughly 67% real-fraud precision in backtesting -- one of its strongest signals.",
        "expected_pct": 67,
    },
    "MEDIUM": {
        "note": "This falls in the model's mid anomaly-score band, which validated at "
                "roughly 34% real-fraud precision in backtesting -- a moderate-confidence signal.",
        "expected_pct": 34,
    },
    "LOW": {
        "note": "This falls in the model's lower anomaly-score band, which validated at "
                "roughly 1% real-fraud precision in backtesting -- likely benign, retained for completeness.",
        "expected_pct": 1,
    },
}


def _percentages_in(text: str) -> list:
    return [float(n) for n in re.findall(r"(\d+(?:\.\d+)?)\s*%", text)]


def narrate_sar(sender: str, receiver: str, amount: float, risk_level: str,
                 reason: str, timeout: int = 8) -> str:
    """
    Returns one grounded narrative sentence describing the flagged
    transaction, or raises on any failure -- the caller is expected to
    catch this and fall back to the plain deterministic SAR text.

    Retries once on HTTP 429 (rate limit) after a short pause -- Groq's
    free tier occasionally rejects a request even within the app's own
    20-row-per-query cap, and a single retry clears most of those.
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError("GROQ_API_KEY not set -- SAR narration unavailable")

    # Pure ML-score hits (no rule-based mechanism in the reason text) don't give the
    # model much to describe beyond the raw score -- swap in the validated
    # tier-precision framing instead so the sentence adds real information rather
    # than paraphrasing a number. The raw score is deliberately dropped from the
    # prompt in this case (not just "don't restate it") -- a small model shown both
    # the 0-1 score and the tier percentage in the same prompt will sometimes
    # conflate the two (e.g. turn a 0.636 score into a fabricated "63%").
    expected_pct = None
    if reason.strip().startswith("Flagged by anomaly detection model") and "|" not in reason:
        tier = _ML_ONLY_TIER_CONTEXT.get(risk_level)
        if tier:
            reason = "Flagged by anomaly detection model (elevated anomaly score)"
            expected_pct = tier["expected_pct"]

    user_prompt = (
        f"Sender: {sender}\n"
        f"Receiver: {receiver}\n"
        f"Amount: ${amount:,.2f}\n"
        f"Risk level: {risk_level}\n"
        f"Reason flagged: {reason}"
    )
    if expected_pct is not None:
        user_prompt += f"\nConfidence context: {_ML_ONLY_TIER_CONTEXT[risk_level]['note']}"

    payload = {
        "model": GROQ_MODEL,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.3,
        "max_tokens": 80,
    }
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}

    for attempt in (1, 2):
        response = requests.post(GROQ_API_URL, headers=headers, json=payload, timeout=timeout)
        if response.status_code == 429 and attempt == 1:
            time.sleep(1.5)
            continue
        response.raise_for_status()
        break

    sentence = response.json()["choices"][0]["message"]["content"].strip()
    if not sentence:
        raise ValueError("LLM returned empty narration")

    # Safety net: if we gave the model a specific validated percentage, any
    # percentage figure it prints MUST match (within rounding tolerance). A
    # mismatch means it fabricated or conflated a number -- reject rather than
    # ship a wrong statistic in a compliance document; caller falls back to the
    # plain deterministic template.
    if expected_pct is not None:
        found = _percentages_in(sentence)
        if found and not any(abs(p - expected_pct) <= 3 for p in found):
            raise ValueError(
                f"LLM stated percentage(s) {found} don't match validated {expected_pct}% -- rejecting"
            )

    return sentence
